name = technic_many_machines
title = Extra Technic Machines
description = Adds more technic machines, tested with technic plus beta
depends = technic, moreores, default
optional_depends = maptools, techage, underch, too_many_stones, darkage, unified_inventory
